# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: events/v1/ingest.proto for package 'events.v1'

require 'grpc'
require 'events/v1/ingest_pb'

module Events
  module V1
    module IngestorService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'events.v1.IngestorService'

        rpc :Record, stream(::Events::V1::Event), ::Google::Protobuf::Empty
      end

      Stub = Service.rpc_stub_class
    end
  end
end
