# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: health/v1/health.proto for package 'health.v1'

require 'grpc'
require 'health/v1/health_pb'

module Health
  module V1
    module Health
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'health.v1.Health'

        rpc :Check, ::Health::V1::HealthCheckRequest, ::Health::V1::HealthCheckResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
